# Generated by Django 4.2.7 on 2025-01-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductData',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategory',
        ),
    ]
