# Generated by Django 4.2.7 on 2025-01-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_rename_productdata_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category',
            new_name='name',
        ),
    ]
