# Generated by Django 4.2.7 on 2025-01-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_rename_category_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
