# Generated by Django 4.2.17 on 2025-01-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0007_rename_customer_name_order_customer_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
    ]
