# Generated by Django 4.2.17 on 2025-02-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
